version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: vet_clinic_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      # The default database
      POSTGRES_DB: vet_clinic_gateway
    # Using 5433 on the host because your mi-postgres container already uses 5432!
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  pgdata:
